AutoparkWebEF/Controllers/OrderItemViewModelController.cs
using AutoMapper;
using AutoparkWebEF.BLL.DTO;
using AutoparkWebEF.BLL.Interfaces;
using AutoparkWebEF.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoparkWebEF.Controllers
{
    public class OrderItemViewModelController : Controller
    {
        IService<OrderItemDto> db;

        public OrderItemViewModelController(IService<OrderItemDto> context)
        {
            db = context;
        }

        public IActionResult ViewOrderItems()
        {
            var orderItemDtos = db.GetAll();
            
            // TODO: Need to find out another way for mapping. Looks pretty ugly. You can try to use Profiles or CreateMap method in Startup. As you wish.
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<OrderItemDto, OrderItemViewModel>().ForMember(dest => dest.SparePartName, act => act.MapFrom(src => src.Detail.Name))).CreateMapper();
            var orderItems = mapper.Map<IEnumerable<OrderItemDto>, List<OrderItemViewModel>>(orderItemDtos);
            return View(orderItems);
        }

        public async Task<IActionResult> OrderItemDetails(int id)
        {
            var orderItemDto = await db.Get(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<OrderItemDto, OrderItemViewModel>().ForMember(dest => dest.SparePartName, act => act.MapFrom(src => src.Detail.Name))
            .ForMember(dest => dest.VehicleName, act => act.MapFrom(src => src.Order.Vehicle.ModelName))).CreateMapper();
            var orderItem = mapper.Map<OrderItemDto, OrderItemViewModel>(orderItemDto);

            return View(orderItem) ?? (IActionResult)NotFound();
        }

        public IActionResult CreateOrderItem()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrderItem(OrderItemViewModel orderItem)
        {
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<OrderItemViewModel, OrderItemDto>()).CreateMapper();
            var orderItemDto = mapper.Map<OrderItemViewModel, OrderItemDto>(orderItem);
            await db.Create(orderItemDto);
            return RedirectToAction("ViewOrderItems");
        }
    }
}

AutoparkWebEF/Controllers/OrderViewModelController.cs
using AutoMapper;
using AutoparkWebEF.BLL.DTO;
using AutoparkWebEF.BLL.Interfaces;
using AutoparkWebEF.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoparkWebEF.Controllers
{
    public class OrderViewModelController : Controller
    {
        IService<OrderDto> db;

        public OrderViewModelController(IService<OrderDto> context)
        {
            db = context;
        }

        public IActionResult ViewOrders()
        {
            var orderDtos = db.GetAll();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<OrderDto, OrderViewModel>().ForMember(dest => dest.VehicleName, act => act.MapFrom(src => src.Vehicle.ModelName))).CreateMapper();
            var orders = mapper.Map<IEnumerable<OrderDto>, List<OrderViewModel>>(orderDtos);
            return View(orders);
        }

        public async Task<IActionResult> OrderDetails(int id)
        {
            var orderDto = await db.Get(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<OrderDto, OrderViewModel>().ForMember(dest => dest.VehicleName, act => act.MapFrom(src => src.Vehicle.ModelName))).CreateMapper();
            var order = mapper.Map<OrderDto, OrderViewModel>(orderDto);

            return View(order) ?? (IActionResult)NotFound();
        }

        public IActionResult CreateOrder()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrder(OrderViewModel order)
        {
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<OrderViewModel, OrderDto>()).CreateMapper();
            var orderDto = mapper.Map<OrderViewModel, OrderDto>(order);
            await db.Create(orderDto);
            return RedirectToAction("ViewOrders");
        }
    }
}

AutoparkWebEF/Controllers/SparePartViewModelController.cs
using AutoMapper;
using AutoparkWebEF.BLL.DTO;
using AutoparkWebEF.BLL.Interfaces;
using AutoparkWebEF.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoparkWebEF.Controllers
{
    public class SparePartViewModelController : Controller
    {
        IService<SparePartDto> db;

        public SparePartViewModelController(IService<SparePartDto> service)
        {
            db = service;
        }

        public IActionResult ViewSpareParts()
        {
            var partsDtos = db.GetAll();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<SparePartDto, SparePartViewModel>()).CreateMapper();
            var parts = mapper.Map<IEnumerable<SparePartDto>, List<SparePartViewModel>>(partsDtos);
            return View(parts);
        }

        public IActionResult CreateSparePart()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSparePart(SparePartViewModel part)
        {
            var partDto = new SparePartDto { Id = part.Id, Name = part.Name };
            await db.Create(partDto);
            return RedirectToAction("ViewSpareParts");
        }

        [HttpGet]
        [ActionName("DeleteSparePart")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                var partDto = await db.Get(id);
                var part = new SparePartViewModel { Id = partDto.Id, Name = partDto.Name };
                if (part != null)
                    return View(part);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSparePart(int? id)
        {
            if (id != null)
            {
                var partDto = await db.Get(id);
                if (partDto != null)
                {
                    await db.Delete(partDto);
                    return RedirectToAction("ViewSpareParts");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> EditSparePart(int? id)
        {
            if (id != null)
            {
                var partDto = await db.Get(id);
                var part = new SparePartViewModel { Id = partDto.Id, Name = partDto.Name };
                if (part != null)
                    return View(part);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult EditSparePart(SparePartViewModel part)
        {
            if (ModelState.IsValid)
            {
                var partDto = new SparePartDto { Id = part.Id, Name = part.Name };
                db.Update(partDto);
                return RedirectToAction("ViewSpareParts");
            }
            else
                return RedirectToAction("EditSparePart");
        }
    }
}

AutoparkWebEF/Controllers/VehicleTypeViewModelController.cs
using AutoMapper;
using AutoparkWebEF.BLL.DTO;
using AutoparkWebEF.BLL.Interfaces;
using AutoparkWebEF.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoparkWebEF.Controllers
{
    public class VehicleTypeViewModelController : Controller
    {
        IService<VehicleTypeDto> db;

        public VehicleTypeViewModelController(IService<VehicleTypeDto> service)
        {
            db = service;
        }

        public IActionResult ViewVehicleTypes()
        {
            var vehicleTypeDtos = db.GetAll();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<VehicleTypeDto, VehicleTypeViewModel>()).CreateMapper();
            var vehicles = mapper.Map<IEnumerable<VehicleTypeDto>, List<VehicleTypeViewModel>>(vehicleTypeDtos);
            return View(vehicles);
        }

        public IActionResult CreateType()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateType(VehicleTypeViewModel type)
        {
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<VehicleTypeViewModel, VehicleTypeDto>()).CreateMapper();
            var typeDto = mapper.Map<VehicleTypeViewModel, VehicleTypeDto>(type);

            await db.Create(typeDto);

            return RedirectToAction("ViewVehicleTypes");
        }

        [HttpGet]
        [ActionName("DeleteType")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                var typeDto = await db.Get(id);
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<VehicleTypeDto, VehicleTypeViewModel>()).CreateMapper();
                var type = mapper.Map<VehicleTypeDto, VehicleTypeViewModel>(typeDto);
                if (type != null)
                    return View(type);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteType(int? id)
        {
            if (id != null)
            {
                var typeDto = await db.Get(id);
                if (typeDto != null)
                {
                    await db.Delete(typeDto);
                    return RedirectToAction("ViewVehicleTypes");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> EditType(int? id)
        {
            if (id != null)
            {
                var typeDto = await db.Get(id);
                var mapper = new MapperConfiguration(cfg => { cfg.CreateMap<VehicleTypeDto, VehicleTypeViewModel>(); }).CreateMapper();
                var type = mapper.Map<VehicleTypeDto, VehicleTypeViewModel>(typeDto);
                if (type != null)
                    return View(type);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult EditType(VehicleTypeViewModel type)
        {
            if (ModelState.IsValid)
            {
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<VehicleTypeViewModel, VehicleTypeDto>()).CreateMapper();
                var typeDto = mapper.Map<VehicleTypeViewModel, VehicleTypeDto>(type);
                db.Update(typeDto);
                return RedirectToAction("ViewVehicleTypes");
            }
            else
                return RedirectToAction("EditType");
        }
    }
}

AutoparkWebEF/Controllers/VehicleViewModelController.cs
using AutoMapper;

using AutoparkWebEF.BLL.DTO;
using AutoparkWebEF.BLL.Interfaces;
using AutoparkWebEF.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoparkWebEF.Controllers
{
    public class VehicleViewModelController : Controller
    {
        IService<VehicleDto> db;

        public VehicleViewModelController(IService<VehicleDto> service)
        {
            db = service;
        }

        public IActionResult ViewVehicles(SortState sortOrder = SortState.DefaultByID)
        {
            ViewData["ModelName"] = sortOrder == SortState.ModelNameAsc ? SortState.ModelNameDesc : SortState.ModelNameAsc;
            ViewData["Mileage"] = sortOrder == SortState.MileageAsc ? SortState.MileageDesc : SortState.MileageAsc;
            ViewData["TypeName"] = sortOrder == SortState.TypeNameAsc ? SortState.TypeNameDesc : SortState.TypeNameAsc;

            var vehicleDtos = db.GetAll();
            var mapper = new MapperConfiguration(cfg => { cfg.CreateMap<VehicleDto, VehicleViewModel>().ForMember(dest => dest.TypeName, act => act.MapFrom(src => src.Type.TypeName));
                
            }).CreateMapper();

            vehicleDtos = sortOrder switch
            {
                SortState.ModelNameAsc => vehicleDtos.OrderBy(v => v.ModelName),
                SortState.ModelNameDesc => vehicleDtos.OrderByDescending(v => v.ModelName),
                SortState.TypeNameAsc => vehicleDtos.OrderBy(v => v.Type.TypeName),
                SortState.TypeNameDesc => vehicleDtos.OrderByDescending(v => v.Type.TypeName),
                SortState.MileageAsc => vehicleDtos.OrderBy(v => v.Mileage),
                SortState.MileageDesc => vehicleDtos.OrderByDescending(v => v.Mileage),
                _ => vehicleDtos.OrderBy(v => v.Id)
            };

            var vehicles = mapper.Map<IEnumerable<VehicleDto>, List<VehicleViewModel>>(vehicleDtos);
            return View(vehicles);
        }

        public async Task<IActionResult> VehicleDetails(int id)
        {
            var vehicleDto = await db.Get(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<VehicleDto, VehicleViewModel>()
                .ForMember(dest => dest.TypeName, act => act.MapFrom(src => src.Type.TypeName))).CreateMapper();
            var vehicle = mapper.Map<VehicleDto, VehicleViewModel>(vehicleDto);

            return View(vehicle) ?? (IActionResult)NotFound();
        }

        public IActionResult CreateVehicle()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateVehicle(VehicleViewModel vehicle)
        {
            if (ModelState.IsValid)
            {
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<VehicleViewModel, VehicleDto>()).CreateMapper();
                var vehicleDto = mapper.Map<VehicleViewModel, VehicleDto>(vehicle);
                await db.Create(vehicleDto);
                return RedirectToAction("ViewVehicles");
            }

            return RedirectToAction("CreateVehicle");
            
        }

        [HttpGet]
        [ActionName("DeleteVehicle")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                var vehicleDto = await db.Get(id);
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<VehicleDto, VehicleViewModel>()
                .ForMember(dest => dest.TypeName, act => act.MapFrom(src => src.Type.TypeName))).CreateMapper();
                var vehicle = mapper.Map<VehicleDto, VehicleViewModel>(vehicleDto);
                if (vehicle != null)
                    return View(vehicle);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteVehicle(int? id)
        {
            if (id != null)
            {
                var vehicleDto = await db.Get(id);
                if (vehicleDto != null)
                {
                    await db.Delete(vehicleDto);
                    return RedirectToAction("ViewVehicles");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> EditVehicle(int? id)
        {
            if (id != null)
            {
                var vehicleDto = await db.Get(id);
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<VehicleDto, VehicleViewModel>()).CreateMapper();
                var vehicle = mapper.Map<VehicleDto, VehicleViewModel>(vehicleDto);
                if (vehicle != null)
                    return View(vehicle);
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult EditVehicle(VehicleViewModel vehicle)
        {
            if (ModelState.IsValid)
            {
                var mapper = new MapperConfiguration(cfg => {
                    cfg.CreateMap<VehicleViewModel, VehicleDto>();}).CreateMapper();
                var vehicleDto = mapper.Map<VehicleViewModel, VehicleDto>(vehicle);
                db.Update(vehicleDto);
                return RedirectToAction("ViewVehicles");
            }
            else
                return RedirectToAction("EditVehicle");
        }
    }
}

AutoparkWebEF/Views/VehicleViewModel/CreateVehicle.cshtml
@model AutoparkWebEF.Models.VehicleViewModel
@inject AutoparkWebEF.BLL.Interfaces.IService<VehicleTypeDto> type

@{
    ViewData["Title"] = "New Vehicle";
}
<h2>@ViewData["Title"]</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <form asp-action="CreateVehicle" asp-controller="VehicleViewModel">
        <div>
            <div class="form-group">
                <label asp-for="TypeId">Type</label>
                <div>
                    <select name="TypeId" class="form-control">
                        @foreach (var t in type.GetAll())
                        {
                            <option value="@t.Id">@t.TypeName</option>
                        }
                    </select>
                    <p>@Html.ValidationMessageFor(m => m.TypeId)</p>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ModelName"></label>
                <input type="text" asp-for="ModelName" class="form-control" />
                <p>@Html.ValidationMessageFor(m => m.ModelName)</p>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationNumber"></label>
                <input type="text" asp-for="RegistrationNumber" class="form-control" />
                <p>@Html.ValidationMessageFor(m => m.RegistrationNumber)</p>
            </div>
            <div class="form-group">
                <label asp-for="Weight"></label>
                <input asp-for="Weight" class="form-control" />
                <p>@Html.ValidationMessageFor(m => m.Weight)</p>
            </div>
            <div class="form-group">
                <label asp-for="ManufactureYear"></label>
                <input type="number" asp-for="ManufactureYear" class="form-control" />
                <p>@Html.ValidationMessageFor(m => m.ManufactureYear)</p>
            </div>
            <div class="form-group">
                <label asp-for="Mileage"></label>
                <input asp-for="Mileage" class="form-control" />
                <p>@Html.ValidationMessageFor(m => m.Mileage)</p>
            </div>
            <div class="form-group">
                <label asp-for="TankVolume"></label>
                <input asp-for="TankVolume" class="form-control" />
                <p>@Html.ValidationMessageFor(m => m.TankVolume)</p>
            </div>
            <div class="form-group">
                <label asp-for="Color"></label>
                <input type="text" asp-for="Color" class="form-control" />
                <p>@Html.ValidationMessageFor(m => m.Color)</p>
            </div>
            <div class="form-group">
                <label asp-for="Engine"></label>
                <div>
                    <select name="Engine" class="form-control">
                        @{var engineList = Enum.GetValues(typeof(EngineNames));}
                        @for (int i = 0; i < engineList.Length; i++)
                        {
                            <option>@engineList.GetValue(i)</option>
                        }
                    </select>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-secondary" />
            </div>
        </div>
    </form>
}



<div>
    <a class="btn btn-outline-info" role="button" asp-controller="VehicleViewModel" asp-action="ViewVehicles">Back to list of vehicles</a>
</div>

AutoparkWebEF/Views/VehicleViewModel/DeleteVehicle.cshtml
@model AutoparkWebEF.Models.VehicleViewModel
@{
    ViewData["Title"] = "Delete vehicle";
}
<h2>@ViewBag.Title</h2>
<div>
    <dl class="dl-horizontal">
        <dt>Id</dt>
        <dd>
            @Model.Id
        </dd>

        <dt>Type</dt>
        <dd>
            @Model.TypeName
        </dd>

        <dt>Model Name</dt>
        <dd>
            @Model.ModelName
        </dd>

        <dt>Registration Number</dt>
        <dd>
            @Model.RegistrationNumber
        </dd>

        <dt>Weight</dt>
        <dd>
            @Model.Weight
        </dd>

        <dt>Manufacture Year</dt>
        <dd>
            @Model.ManufactureYear
        </dd>

        <dt>Mileage</dt>
        <dd>
            @Model.Mileage
        </dd>

        <dt>Tank Volume</dt>
        <dd>
            @Model.TankVolume
        </dd>

        <dt>Color</dt>
        <dd>
            @Model.Color
        </dd>

        <dt>Engine</dt>
        <dd>
            @Model.Engine
        </dd>
    </dl>

    <div>
        <form asp-controller="VehicleViewModel" asp-action="DeleteVehicle" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-outline-info" value="Delete" />
            </div>
        </form>
    </div>
</div>
<div>
    <a class="btn btn-outline-info" role="button" asp-controller="VehicleViewModel" asp-action="ViewVehicles">Back to list of vehicles</a>
</div>

AutoparkWebEF/Views/VehicleViewModel/EditVehicle.cshtml
@model AutoparkWebEF.Models.VehicleViewModel
@inject AutoparkWebEF.BLL.Interfaces.IService<VehicleTypeDto> type

@{
    ViewData["Title"] = "Edit vehicle";
}
<h2>@ViewData["Title"]</h2>

<form asp-action="EditVehicle" asp-controller="VehicleViewModel">
    <div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="TypeId">Type</label>
            <div>
                <select name="TypeId" class="form-control" asp-for="TypeId">
                    @foreach (var t in type.GetAll())
                    {
                        <option value="@t.Id">@t.TypeName</option>
                    }
                </select>
                <p>@Html.ValidationMessageFor(m => m.TypeId)</p>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ModelName"></label>
            <input type="text" asp-for="ModelName" class="form-control" />
            <p>@Html.ValidationMessageFor(m => m.ModelName)</p>
        </div>

        <div class="form-group">
            <label asp-for="RegistrationNumber"></label>
            <input type="text" asp-for="RegistrationNumber" class="form-control" />
            <p>@Html.ValidationMessageFor(m => m.RegistrationNumber)</p>
        </div>

        <div class="form-group">
            <label asp-for="Weight"></label>
            <input asp-for="Weight" class="form-control" />
            <p>@Html.ValidationMessageFor(m => m.Weight)</p>
        </div>

        <div class="form-group">
            <label asp-for="ManufactureYear"></label>
            <input type="number" asp-for="ManufactureYear" class="form-control" />
            <p>@Html.ValidationMessageFor(m => m.ManufactureYear)</p>
        </div>

        <div class="form-group">
            <label asp-for="Mileage"></label>
            <input asp-for="Mileage" class="form-control" />
            <p>@Html.ValidationMessageFor(m => m.Mileage)</p>
        </div>

        <div class="form-group">
            <label asp-for="TankVolume"></label>
            <input asp-for="TankVolume" class="form-control" />
            <p>@Html.ValidationMessageFor(m => m.TankVolume)</p>
        </div>

        <div class="form-group">
            <label asp-for="Color"></label>
            <input type="text" asp-for="Color" class="form-control" />
            <p>@Html.ValidationMessageFor(m => m.Color)</p>
        </div>

        <div class="form-group">
            <div>
                <label asp-for="Engine"></label>
                <select name="Engine" class="form-control" asp-for="Engine">
                    @{var engineList = Enum.GetValues(typeof(EngineNames));}
                    @for (int i = 0; i < engineList.Length; i++)
                    {
                        <option>@engineList.GetValue(i)</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-outline-info" />
        </div>
    </div>
</form>

<div>
    <a class="btn btn-outline-info" role="button" asp-controller="VehicleViewModel" asp-action="ViewVehicles">Back to list of vehicles</a>
</div>

AutoparkWebEF/Views/VehicleViewModel/VehicleDetails.cshtml
@model AutoparkWebEF.Models.VehicleViewModel
@{
    ViewData["Title"] = "Vehicle Details";
}
<h2>@ViewData["Title"]</h2>
<div>
    <p> </p>
</div>
<form asp-action="VehicleDetails" asp-controller="VehicleViewModel">
    <table class="table table-bordered">
        <caption>Vehicle Details</caption>
        <thead class="thead-dark">
            <tr>
                <th scope="col"><p class="text-center">ID</p></th>
                <th scope="col"><p class="text-center">Type</p></th>
                <th scope="col"><p class="text-center">Model</p></th>
                <th scope="col"><p class="text-center">Number</p></th>
                <th scope="col"><p class="text-center">Weight</p></th>
                <th scope="col"><p class="text-center">Year</p></th>
                <th scope="col"><p class="text-center">Mileage</p></th>
                <th scope="col"><p class="text-center">TankVolume</p></th>
                <th scope="col"><p class="text-center">Color</p></th>
                <th scope="col"><p class="text-center">Engine</p></th>
                <th scope="col"><p class="text-center">Tax per month</p></th>
                <th scope="col"><p class="text-center">Mileage on a full tank</p></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Id</td>
                <td>@Model.TypeName</td>
                <td>@Model.ModelName</td>
                <td>@Model.RegistrationNumber</td>
                <td>@Model.Weight kg</td>
                <td>@Model.ManufactureYear</td>
                <td>@Model.Mileage km</td>
                <td>@Model.TankVolume</td>
                <td>@Model.Color</td>
                <td>@Model.Engine</td>
                <td>@Model.TaxPerMonth.ToString("0.00") $</td>
                <td>@Model.MileageWithFullTank.ToString("0.00") km</td>

            </tr>
        </tbody>
    </table>
</form>

<div>
    <a type="button" class="btn btn-outline-info" asp-controller="VehicleViewModel" asp-action="ViewVehicles">Back to list of vehicles</a>
</div>

AutoparkWebEF/Views/VehicleViewModel/ViewVehicles.cshtml
@model IEnumerable<AutoparkWebEF.Models.VehicleViewModel>
@{
    ViewData["Title"] = "Vehicles";
}
<h2>@ViewData["Title"]</h2>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Vehicles</li>
        <li class="breadcrumb-item"><a asp-controller="VehicleTypeViewModel" asp-action="ViewVehicleTypes">Vehicle Types</a></li>
        <li class="breadcrumb-item"><a asp-controller="SparePartViewModel" asp-action="ViewSpareParts">Spare Parts</a></li>
        <li class="breadcrumb-item"><a asp-controller="OrderViewModel" asp-action="ViewOrders">Orders</a></li>
        <li class="breadcrumb-item"><a asp-controller="OrderItemViewModel" asp-action="ViewOrderItems">Order Items</a></li>
    </ol>
</nav>
<div>
    <p>
        <a class="btn btn-outline-info" role="button" asp-controller="VehicleViewModel" asp-action="CreateVehicle">Add vehicle</a>
    </p>
</div>


<table class="table table-bordered table-hover">
    <caption>List of vehicles</caption>
    <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col"><a asp-controller="VehicleViewModel" asp-action="ViewVehicles" asp-route-sortOrder="@ViewBag.TypeName">Type</a></th>
            <th><a asp-controller="VehicleViewModel" asp-action="ViewVehicles" asp-route-sortOrder="@ViewBag.ModelName">ModelName</a></th>
            <th scope="col">Number</th>
            <th scope="col">Weight</th>
            <th scope="col">Year</th>
            <th><a asp-controller="VehicleViewModel" asp-action="ViewVehicles" asp-route-sortOrder="@ViewBag.Mileage">Mileage</a></th>
            <th scope="col">TankVolume</th>
            <th scope="col">Color</th>
            <th scope="col">Engine</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td><a asp-controller="VehicleViewModel" asp-action="VehicleDetails" asp-route-id="@item.Id">@item.Id</a></td>
                <td>@item.TypeName</td>
                <td>@item.ModelName</td>
                <td>@item.RegistrationNumber</td>
                <td>@item.Weight</td>
                <td>@item.ManufactureYear</td>
                <td>@item.Mileage</td>
                <td>@item.TankVolume</td>
                <td>@item.Color</td>
                <td>@item.Engine</td>
                <td>
                    <a asp-controller="VehicleViewModel" asp-action="EditVehicle" asp-route-id="@item.Id">Update</a> |
                    <a asp-controller="VehicleViewModel" asp-action="DeleteVehicle" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>